services:
  api:
    restart: always
    build: .
    container_name: paf
    ports:
      - "8080:8080"
    environment:
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_RECIPIENTS: ${EMAIL_RECIPIENTS}
      API_PORT: ${API_PORT}